language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
    - python: "nightly"

before_install:
    - pip install -IU pip pipenv

install:
    - pipenv install --dev

script:
    - vint .
    - pylama
    - pytest
